spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
    hikari:
      max-lifetime: 1200000
#  mvc:
#    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static,file:./static
#static-locations: classpath:/static,file:D:/java/IdeaProjects/app-hospital/static

  servlet:
    multipart:
      # 最大支持文件大小
      max-file-size: 10MB

  redis:
    # Redis服务器地址
    host: localhost
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 10000ms
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1024
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000ms
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接
        min-idle: 0

mybatis:
  # mybatis pageHelper 分页配置
  config-location: classpath:/config/SqlMapConfig.xml

server:
  port: 8080
  servlet:
    context-path: /hospital

## 开启 Swagger的 Basic认证功能,默认是false
swagger:
  # 是否关闭 swagger接口文档访问
  #  production: true
  basic:
    # 开启简单用户验证
    enable: true
    # 用户名
    username: hospital
    # 用户密码
    password: hospital

# 自定义 JWT key
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的密钥
  secret: hospital-ChlGPaNSit1wdUBQ0LXDfduI2mFZ
  # JWT的超期限时间(60*60*24 = 一天)
  expiration: 604800
  # JWT负载中拿到开头
  tokenHead: Bearer

# 阿里云短信服务配置
aliSms:
  # 是否开启模拟调用，开启后，验证码均为 123456
  mock: false
  # 阿里云短信服务 key
  accessKeyId: ""
  # 阿里云短信服务 secret
  accessSecret: ""
  # 短信抬头
  signName: ""
  # 注册短信验证码模板
  loginTemplate: "SMS_"
  regionId: "cn-hangzhou"
  domain: "dysmsapi.aliyuncs.com"
  version: "2017-05-25"

# 自定义 redis key 用于存储短信验证码
redis:
  key:
    prefix:
      authCode: "hospital:register:authCode:"
    expire:
      # 验证码超时时间,默认 5分钟
      authCode: 300
app:
  file:
    domain: "http://localhost:8080/hospital"
    address: "./static/img"


# 七牛云文件存储
qiniu:
  accessKey:
  secretKey:
  bucket: yujian-hospital
  # 访问域名前缀
  url: http://q59ifzu6u.bkt.clouddn.com/

secure:
  ignored:
    urls: #安全路径白名单
      - /**


# 小程序配置，用于调用官方API
wx:
  appId:
  appSecret: