#version: '3'
#networks:
#  loki:
#    ipam:
#      driver: default
#      config:
#        - subnet: "172.22.0.0/24"
#          gateway: 172.22.0.1
#services:
#  mysql:
#    image: mysql:5.7
#    container_name: mysql5__7
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_PASSWORD: root
#      MYSQL_DATABASE: yygh_hosp
#      TZ: Asia/Shanghai #时区
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ~/mysql/data:/var/lib/mysql
#    restart: no
#    networks:
#      loki:
#        ipv4_address: 172.22.0.2
#
#  mongo:
#    container_name: mongo_4
#    image: mongo:4.4
#    volumes:
#      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#      #这是c盘用户地址
#      - ~/mongodb/data:/data/db
#    ports:
#      - "27017:27017"
#    restart: no
#    command: mongod
#    networks:
#      loki:
#        ipv4_address: 172.22.0.3
#  front-admin:
#    build: ./front
#    container_name: front-admin
#    image: front-admin:0.0.1
#    ports:
#      - 9528:9528
#    networks:
#      loki:
#        ipv4_address: 172.22.0.4
#  front-user:
#    build: front-user
#    container_name: front-user
#    image: front-user:0.0.1
#    ports:
#      - 3000:3000
#    depends_on:
#      - hospital-service
#    networks:
#      loki:
#        ipv4_address: 172.22.0.6
#  hospital-service:
#    build: ./hosp-service
#    image: hosp-service:0.0.1
#    container_name: hosp-service
#    restart: no
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#      - SPRING_DATA_MONGODB_HOST= mongo
#    ports:
#      - 8088:8088
#      - 5005:5005
#    depends_on:
#      - mongo
#      - mysql
#    networks:
#      loki:
#        ipv4_address: 172.22.0.5