version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql5__7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: yygh_hosp
      TZ: Asia/Shanghai #时区
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ~/mysql/data:/var/lib/mysql
    restart: always

  mongo:
    container_name: mongo_4
    image: mongo:4.4
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ~/mongodb/data:/data/db
    ports:
      - "27017:27017"
    restart: always
    command: mongod

  hospital-service:
    build: ./hosp-service
    image: hosp-service:0.0.1
    container_name: hosp-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATA_MONGODB_HOST= mongo
    ports:
      - 8088:8088
      - 5005:5005
    depends_on:
      - mongo
      - mysql